### PR TITLE
Translated to Vietnamese

### PR DESCRIPTION
**Pull request by duongtiendat1990**
Dear Peter Cottle, please review this merge request. I've translated all content to Vietnamese. Hopefully, this will be merged soon so that all Vietnamese developer can learn git branching through your amazing app.

### CODE REVIEW

**Comment by pcottle** [comment]
Oh wow this is absolutely amazing @duongtiendat1990 !!

Do you mind trying to resolve/fix those two merge conflicts? It's only two files but shouldn't be too bad. Then we can merge this cleanly!

**Comment by duongtiendat1990** [comment]
Dear @pcottle, I've resolved those conflicts. Pls, take a look and inform me if anything need to be done to my translate get online.

**Comment by pcottle** [comment]
Looks great @duongtiendat1990 :D And thanks for translating this app despite it being so difficult to translate (with all the JSON and repeated data). I'll merge this and push it into the site now

**Comment by pcottle** [comment]
https://learngitbranching.js.org/?locale=vi

Looks great!

**Pull request merged**
