### PR TITLE
Update gulpfile.js

### PR DESCRIPTION
**Pull request by iantolan11**
fixed issue with goal not initializing

### CODE REVIEW

**Comment by iantolan11** [comment]
For issue #688

**Comment by hong4rc** [comment]
Merged #686, It can't fix #688, I will create a PR to fix it

**Comment by pcottle** [comment]
I don't think this is needed anymore since we require jquery ui via an explicit require statement and it's packaged in the overall bundle via yarn 🤔

**Comment by pcottle** [comment]
Gonna close this out since I don't think its required :)

**Pull request closed without merging**
