### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by coyl**
* Translated all the levels except "remote" section
* Translated all system messages
* Fork master updated before merging.

### CODE REVIEW

**Comment by pcottle** [comment]
Thanks a bunch for the rebase! I think there was only a small mistake in `src/levels/mixed/tags.js` where it seems some english was added to the japanese and then some japanese was replaced by russian? see screenshot

screen shot 2015-05-05 at 6 39 33 pm

they rest all looks good though! :fireworks: :confetti_ball:

So I see two options:
1) I merge this PR as-is and then simply revert the changes to `src/levels/mixed/tags.js` and let you followup with another PR
2) we re-diff the whole thing with the changes included

I'm leaning towards #1 actually since thats probably less work for you

**Comment by pcottle** [comment]
Alright reverted the changes to `tags.js` and pushed to prod!

Only issue is that ugly width / centering bug on the levels dialog is super nasty :*( ill file an issue for this, i should get off my butt and fix it

**Comment by coyl** [comment]
Thanks a lot for fixing my mistake =) It probably appeared when I resolved conflicts after updating master.

**Comment by pcottle** [comment]
Yeah it's tough to rebase these diffs! Do you want to send another PR for
the tags level? All I did was actually revert it to a state without Russian
since I couldn't double check the work but it should be fairly easy to
rearrange and fix up I imagine. Let me know!

On Wednesday, May 6, 2015, Vasiliy coylOne Kulakov <notifications@github.com>
wrote:

> Thanks a lot for fixing my mistake =) It probably appeared when I resolved
> conflicts after updating master.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pcottle/learnGitBranching/pull/265#issuecomment-99397762>
> .
>


-- 
-Sent from Gmail Mobile

**Comment by coyl** [comment]
Yes, I will send new PR a bit later.

**Comment by pcottle** [comment]
Great! No rush, just making sure you realized i didnt put up the _full_
fix. thanks again

On Wed, May 6, 2015 at 7:30 AM, Vasiliy coylOne Kulakov <
notifications@github.com> wrote:

> Yes, I will send new PR a bit later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pcottle/learnGitBranching/pull/265#issuecomment-99491321>
> .
>



-- 
Peter M Cottle
UC Berkeley Class of 2012
Master's of Science, Mechanical Engineering
UC San Diego Class of 2011
Bachelor's of Science, Mechanical Engineering
(408) 455 9405

"Equipped with his five senses, man explores the universe around him and
calls the adventure Science." - Edwin Hubble

**Pull request merged**
