### PR TITLE
Move tests to the root

### LINKED ISSUE #359: Demo is broken by recent updates
Demo on [gh-pages](http://pcottle.github.io/learnGitBranching/) seems broken.

There's an error message in the console:

```js
Uncaught ReferenceError: describe is not defined
```

### PR DESCRIPTION
**Pull request by sameoldmadness**
fixes #359

### CODE REVIEW

**Comment by sameoldmadness** [comment]
I could not understand why `ignore` option is not working, so I've just moved the tests out of browserify's scope for now.

**Comment by pcottle** [comment]
Thank you @sameoldmadness for saving the day!! :heart: 

If you look at the recent PR's we had to upgrade the version of browserify and grunt-browserify in order to fix the travis CI build. once browserify worked cleanly and all the tests passed I figured it was good, but clearly I should have checked the actual build.

pushing this to prod now

**Comment by pcottle** [comment]
screen shot 2016-02-14 at 12 25 02 pm

fixed! thanks again :+1:

**Comment by sameoldmadness** [comment]
I'm happy to contribute in such a great tool : )

btw the update was inevitable – browserify@v3 refuses to install due to some dependency error.

**Pull request merged**
