### PR TITLE
Fix Korean translation

### PR DESCRIPTION
**Pull request by DAUN3046**
Fixed Korean translation to be more natural.
- Removed "당신" at the beginning of sentences in Korean
- Unified terminology
- Fixed other subtle nuance

### CODE REVIEW

**Comment by pcottle** [comment]
@DAUN3046 you closed this merge request without the changes being incorporated into `main`! Would you still like to make these edits?

I don't know Korean so I can't tell if these should be included or not 😅

**Comment by pcottle** [comment]
going to try to reopen...

**Comment by pcottle** [comment]
Just copied over your changes manually @DAUN3046 since I had trouble re-opening the PR, but let me know if you want to submit a trivial change so you're officially counted as a contributor!

Thanks for the great update here 🙌🏻 I had a coworker who understands Korean review the changes and she was impressed with the quality

**Comment by DAUN3046** [comment]
I've temporarily closed the PR due to the need for additional spelling corrections - thanks for the reflection!

**Pull request closed without merging**
