### PR TITLE
[feat] update url if user change locale

### PR DESCRIPTION
**Pull request by Hongarc**
Add locale in `href`

If the user turns off the browser and opens it again, they keep their's locale

Oh, build have error(I cannot test in my local because I am attempting #654)

Wait for me fix this Travis error

### CODE REVIEW

**Comment by pcottle** [comment]
Oh wait there’s one test failure. Can we make the lookup of document null safe so it’ll pass in a node environment?

‘’’
Failures:
623
624  1) LocaleStore changes locales
625   Message:
626     ReferenceError: document is not defined
627   Stacktrace:
628     ReferenceError: document is not defined
629  at Object.changeLocale

**Comment by Hongarc** [comment]
> Will this trigger if we are just changing the locale from a browser header though?

@pcottle Yes, I updated it to auto-detect all case

**Comment by pcottle** [comment]
Even better! thanks doing the util browser check -- wanted to keep those tests healthy

**Comment by pcottle** [comment]
(I'll push the site with these changes shortly when I'm on my home computer)

**Pull request merged**
