### PR TITLE
More French locale updates

### PR DESCRIPTION
**Pull request by nlehuby**

### CODE REVIEW

**Comment by pcottle** [comment]
great thanks a bunch! always appreciative :+1:

**Comment by pcottle** [comment]
```
Writing objects: 100% (9/9), 137.00 KiB | 0 bytes/s, done.
Total 9 (delta 6), reused 0 (delta 0)
To git@github.com:pcottle/learnGitBranching.git
   170d6a7..8ba6800  gh-pages -> gh-pages
```

this PR and your earlier one should be in production now! thanks a ton :D

**Comment by pcottle** [comment]
screen shot 2015-04-03 at 4 16 58 pm
yep its there!

**Comment by nlehuby** [comment]
nice :+1: 
great job by the way !

**Comment by pcottle** [comment]
Thanks! I've actually been updating the app a lot recently to use Flux (and eventually React), which then means I can move over to using react native:
http://facebook.github.io/react-native/

for potentially an iphone app version! It's still far out (a lot of refactoring to do) but its been good motivation to clean everything up recently

**Pull request merged**
