### PR TITLE
Italian translation of not translated levels (start with clone.js in remote level)

### PR DESCRIPTION
**Pull request by egiantu**
Hi
This is my first translation on learnGitBranching e my first pull request on GitHub.

### CODE REVIEW

**Comment by pcottle** [comment]
Looks great!!

**Comment by pcottle** [comment]
(Ill wait a few days to push the site in case you have any other PRs coming, its easier to do in one batch)

**Comment by pcottle** [comment]
pushed it to production, @egiantu  feel free to reload the site and see your changes :)

**Comment by egiantu** [comment]
> pushed it to production, @egiantu feel free to reload the site and see your changes :)

Hi, Peter, I have reload the site, but I don't see changes. I load site with another browser too, but there aren't changes.

Regards

**Comment by pcottle** [comment]
Oh good catch -- this was just an issue with renaming `master` to `main`. think it just got actually pushed now:
https://github.com/pcottle/learnGitBranching/commits/gh-pages

**Pull request merged**
