### PR TITLE
Add `draggable` of `jquery-ui`

### LINKED ISSUE #687: [WebSite broken] Uncaught TypeError: this.$terminal.draggable is not a function
This problem happens on https://learngitbranching.js.org/ and on master (local build).

When trying to do the first exercise it currently brings the following error:
```
Uncaught TypeError: this.$terminal.draggable is not a function
```

`hide goal` won't work and as well the window is not draggable.

I guess that this is due to one of the recent jQuery related commits. But I am just guessing.

### LINKED ISSUE #688: Unable to get past "hide goal" phase at the very first tutorial
Hello,

I was unable to do anything after the "Goal To Reach" window pops up. When I click any of the window buttons of the goal window, nothing happened. Then I tried to write down `hide goal` on the console; no luck either. 

This error comes up on the browser console: `this.goalVis is undefined`

I tried this on an Ubuntu Linux, Firefox, Brave and Chrome's latest browsers. I saw the issue on every one of them

Thanks!

### PR DESCRIPTION
**Pull request by hong4rc**
Fixed #687 and fixed #688

### CODE REVIEW

**Comment by hong4rc** [comment]
Please wait to me check all errors.

**Comment by hong4rc** [comment]
@pcottle Can you check it?

**Comment by lobanko** [comment]
I cannot check all functionality.
but i'm allready check that this pull request exactly repairs linked issues

**Comment by lobanko** [comment]
Thank you guys for good product:)

**Comment by pcottle** [comment]
Gogogo! Sorry for sleeping on this one -- I *swear* the draggable function worked when I commented on #682 when I refreshed from prod. Maybe the branch hadn't fully deployed yet or something.

Ill try to merge this and push ASAP

**Pull request merged**
