### PR TITLE
#937 - Solution proposal

### PR DESCRIPTION
**Pull request by Netz00**
Waiting for comment, all tests passed.
I will add tests for this feature after it's approval.

### CODE REVIEW

**Comment by pcottle** [comment]
Alright super close! This definitely resets the animation but I think it also prevents *advancing* to the next screen. When I tried it out using the green "right" arrow to advance through the lesson, I just got stuck in the loop of going to the reset button -> back to the original starting point, but I could never advance to the next part of the lesson.

I think this is because that `positive` method just puts us in a loop. I think we would need to do something like this:

```
onResetButtonClick: () => {
  this.demonstrated = false;
  this.takeControl();
}
```

and then just wire up the button click

Screenshot 2023-05-04 at 4 39 33 PM
Screenshot 2023-05-04 at 4 39 24 PM

**Comment by Netz00** [comment]
Yeah, sorry for that. I completely forgot to check it🤦🏻‍♂️. Should be fixed with the last commit.
I am glad the rest is okay, and I am not sure if I should add some tests.

**Comment by pcottle** [comment]
Looks great! Going to do two little polish things (change it to "Reset Animation" and maybe fade it out a bit) but thanks so much :D

**Comment by pcottle** [comment]
Screenshot 2023-05-05 at 4 06 03 PM

**Pull request merged**
