### PR TITLE
Added Russian translation for lesson "Git fetch arguments"

### PR DESCRIPTION
**Pull request by alexeiberkov**
Added Russian translation (ru_RU) for lesson "Git fetch arguments" (pushArgs.js). Fixed few typos as well.

### CODE REVIEW

**Comment by pcottle** [comment]
:tada: thanks a bunch!

**Comment by pcottle** [comment]
btw a lot of russian users! thx again

screen shot 2015-11-05 at 8 17 13 am

**Comment by alexeiberkov** [comment]
You are welcome !
At the company where I work we use your lessons as one of the education course ;)

**Comment by pcottle** [comment]
Oh cool! Yeah I think Uber uses it as well -- hopefully its not too bad as a learning exercise / homework assignment.

**Pull request merged**
