### PR TITLE
feat: command to simulate Merge/Pull Request

### PR DESCRIPTION
**Pull request by Magador**
- Adds `git merge(M|P)R <source_branch> <target_branch> [--delete-after-merge]` command to simulate a Merge/Pull Request being merged into the target branch
- The optional flag `--delete-after-merge` will remove the merged branch on the origin tree
  - The local remote branch remains as it is Git default behavior, even after `git fetch` (it would require `git fetch --prune` support to automatically prune remote tracking branches)
- You can push a branch with a deleted remote tracking branch on origin, the ref will just update.

Resolves #1057

### Merging a feature branch `feat` into `main` on `origin`

```sh
git clone;
git switch -c feat;
git commit;
git push;
git fakeTeamwork;
git mergeMR feat main;
```

image

### Merging a feature branch `feat` into `main` on `origin` when deleting it after merging

```sh
git clone;
git switch -c feat;
git commit;
git push;
git fakeTeamwork;
git mergeMR feat main --delete-after-merge;
```

image

If you `git fetch` after using `git mergeMR`, the ref `o/feat` will still exist because `git fetch` does not prune it by default:

```sh
git fetch;
```

image

You can re-push the local branch, re-creating a remote branch, and updating the ref `o/feat`:

```sh
git commit;
git push;
```

image

### CODE REVIEW

**Comment by pcottle** [comment]
Wow @Magador I really appreciate the contribution! You wrote tests and explained the small change in the git engine and thought about everything 🙌🏻

I'm not super familiar with these alternate workflows for merging features (at Instagram we all just merge into one main trunk branch) but sounds like you've thought about these a lot. I'll merge and push the site now with the updates 😎

**Comment by IT-VBFK** [comment]
Yeah :)

thanks @Magador

**Comment by HenryChan-Git** [comment]
that's good ! Where can i do this experiment ? I do not find this one in https://learngitbranching.js.org/?locale=zh_CN

**Comment by Magador** [comment]
> that's good ! Where can i do this experiment ? I do not find this one in https://learngitbranching.js.org/?locale=zh_CN

You can simulate a merge using the [sandbox](https://learngitbranching.js.org/?locale=zh_CN&NODEMO=) and creating a remote repo :

```sh
git clone;
git switch -c feat;
git commit;
git push;
git fakeTeamwork;
git mergeMR feat main;
```

**Comment by HenryChan-Git** [comment]
yes, it works

**Pull request merged**
