### PR TITLE
fix(readme): hide comment in README.md

### PR DESCRIPTION
**Pull request by Hongarc**
image

Hide `[//]: contributor-faces` in `README.md`

### CODE REVIEW

**Comment by pcottle** [comment]
lol i couldnt even do this correctly... thanks!

**Comment by pcottle** [comment]
hrm, seems theres a conflict now :-/

**Comment by pcottle** [comment]
there we go

**Comment by Hongarc** [comment]
And I think you add image contributor under Gitpod is not a good idea, I think we should add it under **Helpful Folks**

**Pull request merged**
