### PR TITLE
Italian transl

### LINKED ISSUE #811: Italian translation missing
Hi I saw that Italian translation is missing, and to thank you for your amazing job I want to help you out in this. I've almost done the local one. One last check, and I'll make a pull request. 
P.S. : I might need a little help cause I'm new in this

### PR DESCRIPTION
**Pull request by ShardanaSoft**
As promised, all local levels. I did not have enough knowledge yet about remote. I'll come back.

I ask here to not open issues (maybe I've missed them): 

1. command `locale`, is not shown in `show commands`
2. I've not found a list of all languages
3. I've build and tested, once I open the index.html file it starts with `index.html?locale=it_IT`, I've messed up or is the correct behavior? (like it detects my country or dunno)

this close #811

### CODE REVIEW

**Comment by pcottle** [comment]
> I did not have enough knowledge yet about remote.

No worries, this is a HUGEEE contribution and thank you so much @ShardanaSoft !

> I've build and tested, once I open the index.html file it starts with index.html?locale=it_IT, I've messed up or is the correct behavior? (like it detects my country or dunno)

yes it should actually detect your browser language headers and convert that into the locale locally, so that functionality is working as intended it seems.

locale is not listed as a command since its not a super helpful command on its own, since you have to type in a given locale code. this language menu is the better option for that:
Screen Shot 2021-03-17 at 8 03 42 AM

**Comment by pcottle** [comment]
This is where you'd want to add a mapping:
https://github.com/pcottle/learnGitBranching/blob/d1a5d9795b6d85afa62dad608485bbc59078787e/src/js/react_views/IntlHelperBarView.jsx

I can do this real quick

**Comment by pcottle** [comment]
Oh and you already added a mapping there, perfect :D 

Site should be pushed with your translation! Feel free to share with any Italians who want to learn git

**Comment by ShardanaSoft** [comment]
Your app saved me a ton of headache. And it's free, this was the least I could do. Also you helped me out with pull request for this translation. I wished to have known this before.

> this language menu is the better option for that:
I've missed it. where do I find this menu? 

Nice I saw you pushed it. seems all good 😃

**Pull request merged**
