### PR TITLE
Fixed many fetch/pull issues on #1138

### PR DESCRIPTION
**Pull request by juanmv94**

### CODE REVIEW

**Comment by juanmv94** [comment]
Need to make some little fix to my changes...

**Comment by juanmv94** [comment]
Looks like all compilation issues are related to tests expecting different (incorrect) results that were addressed by the fixes. Tests might need corrections:

* **doesn't fetch if out of sync, but will update explicit dest if specified**
o/main gets updated after _git fetch origin main:main_ but wasn't updated before correction

* **correctly resolves source during git fetch with params**
**correctly resolves existing commits and updates**
**doesn't let you fetch to main if you are checked out there**
Does unallowed _git fetch origin foo^:blah_

* **pulls to a new branch and then merges in that branch**
o/main gets updated after  _git pull origin main:bar_ but wasn't updated before correction

**Comment by pcottle** [comment]
Yeah I totally agree that we shouldn't *teach* the functionality here that doesnt work (hence why I redid the lesson), but I hesitate to actually break the functionality.

There might be others relying upon this for levels in gists or with hardcoded commands, and adding the validation code might break that :/

will think on this but it seems like a lower priority item compared to updating the lesson (which we did)

**Comment by pcottle** [comment]
Alrighty, looks like everything is passing! Appreciate all the updates here and the work @juanmv94 :)

Will merge and push

**Pull request merged**
