### PR TITLE
Update package

### PR DESCRIPTION
**Pull request by Hongarc**
Up to date all package(exclude `grunt-jasmine-node` and `underscore`)

### CODE REVIEW

**Comment by Hongarc** [comment]
Are you using `Yarn` or `npm`?
You should update `package-lock.json` or `yarn.lock`.

**Comment by pcottle** [comment]
What’s with the babel additions? Don’t remember depending on that

**Comment by Hongarc** [comment]
Because `grunt-jshint` said that need it.

**Comment by pcottle** [comment]
oooh probably to be able to lint JSX. i see. shouldnt it be an internal dependency of `grunt-jsxhint`? yeah we can keep this, theres no active development in the jsx code but I guess its nice to have

**Comment by eatdrinksleepcode** [comment]
This change causes both "npm install && grunt build" and "yarn install && grunt build" to fail with this error:

```
Running "browserify:dist" (browserify) task
>> Error: Cannot find module 'jquery' from '/Users/danelson/Projects/personal/learnGitBranching/node_modules/backbone'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
```

Travis runs only "grunt test", not "grunt build" which is why it was not caught.

**Comment by Hongarc** [comment]
@eatdrinksleepcode Yes, I saw, I am fixing it (and other error when I update `react`).

**Comment by pcottle** [comment]
Cool, lets just revert it in the meantime so any newcomers won't get tripped up by this

**Pull request merged**
