### PR TITLE
fix japanese typos and add ja contents

### PR DESCRIPTION
**Pull request by mizunashi-mana**
I fixed typos and added some ja contents.

### CODE REVIEW

**Comment by pcottle** [comment]
Wow this is a huge amount of work! :clap: :tada: the build looks good so I'll merge this in and try to push to prod by tonight

**Comment by pcottle** [comment]
Feel free to add yourself to the translators list if you aren't there already! (On mobile so can't check)

**Comment by mizunashi-mana** [comment]
Oh, thanks.  Some works of remote section will be probably done soon, so i add then and request with it.

**Comment by pcottle** [comment]
Sweet! Thanks again @mizunashi-mana, I just pushed this out to prod so it should be reflected if you refresh:


```
[gh-pages 9f4af12] rebuild for prod
 4 files changed, 280 insertions(+), 59 deletions(-)
 rename build/{bundle.min.5811461a.js => bundle.min.2f6625fa.js} (81%)
Counting objects: 13, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 189.51 KiB | 0 bytes/s, done.
Total 8 (delta 5), reused 0 (delta 0)
To git@github.com:pcottle/learnGitBranching.git
   4fa5c99..9f4af12  gh-pages -> gh-pages
```

**Pull request merged**
