### PR TITLE
Deleted repetition of the word "aver" in the Italian translation

### PR DESCRIPTION
**Pull request by G-Alessandro**
Deleted repetition of the word "aver" in the Italian translation.

I take this opportunity to thank you immensely for the work you have done which is helping me to better understand how github works in my study path. Sorry if I made some mistakes but English is not my native language and I'm using google translate to write, thanks again for the work you have done and I wish you all the best in your future and future projects.

### CODE REVIEW

**Comment by pcottle** [comment]
Thank you so much! Your English is totally fine :) wish you the best in your studies

**Comment by pcottle** [comment]
(I merged this for now but still need to deploy the update to the site, I got a new laptop so might take a bit...)

**Comment by pcottle** [comment]
think I got it!

**Comment by G-Alessandro** [comment]
It worked perfectly, thanks again for all you do.

**Pull request merged**
