### PR TITLE
Russian translation for the "tags" level

### PR DESCRIPTION
**Pull request by coyl**
* Added translation to the tags.js

### CODE REVIEW

**Comment by pcottle** [comment]
:zap:  :fireworks: !!

**Comment by pcottle** [comment]
should be pushed to prod now. thanks again!

**Comment by coyl** [comment]
Prod is on http://pcottle.github.io/learnGitBranching ? I can't see the russian in language choice panel.

**Comment by pcottle** [comment]
Ah yeah those get added manually. In the meantime you can just do "locale
ru_RU" in the console to change it, but I'll add it today when I wake up

On Thursday, May 7, 2015, Vasiliy coylOne Kulakov <notifications@github.com>
wrote:

> Prod is on http://pcottle.github.io/learnGitBranching ? I can't see the
> russian in language choice panel.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pcottle/learnGitBranching/pull/267#issuecomment-99805827>
> .
>


-- 
-Sent from Gmail Mobile

**Comment by pcottle** [comment]
Also if you could send over the word for "Russian" in actual Russian that
would help! Otherwise I'll just google it

On Thursday, May 7, 2015, Peter Cottle <petermcottle@gmail.com> wrote:

> Ah yeah those get added manually. In the meantime you can just do "locale
> ru_RU" in the console to change it, but I'll add it today when I wake up
>
> On Thursday, May 7, 2015, Vasiliy coylOne Kulakov <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Prod is on http://pcottle.github.io/learnGitBranching ? I can't see the
>> russian in language choice panel.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pcottle/learnGitBranching/pull/267#issuecomment-99805827>
>> .
>>
>
>
> --
> -Sent from Gmail Mobile
>


-- 
-Sent from Gmail Mobile

**Comment by coyl** [comment]
"Russian" in Russian is Русский =)

**Comment by pcottle** [comment]
screen shot 2015-05-07 at 12 38 28 pm

should be there now! pushing prod... also that dialog centering bug is super annoying me now! going to take a crack at it this weekend perhaps...

**Pull request merged**
