### PR TITLE
Translated the rest into Korean

### PR DESCRIPTION
**Pull request by JuhoKang**
Last translation unless there are mistranslations.
Wonder if there  is a entry point for specific language like at the demo.
kind of like this http://pcottle.github.io/learnGitBranching/?demo&locale=ko

It was really fun while doing the translation works. :smile:

### CODE REVIEW

**Comment by JuhoKang** [comment]
I can't get the details of the build failure from the travis page. My builds are passing in my local machine with no problems. It might be minor grammer problems or something else. Can  you please check it for me?.

**Comment by JuhoKang** [comment]
Now I saw the details and the travis build just gone wrong don't know why.

**Comment by pcottle** [comment]
yeah the build failure looks weird -- lemme try to pull this down and test locally

**Comment by pcottle** [comment]
#355 for the other test. it built and passed locally for me too

**Comment by pcottle** [comment]
this is the last part of the output:

```
Found PhantomJS at /usr/local/phantomjs/bin/phantomjs ...verifying
Writing location.js file
PhantomJS is already installed on PATH at /usr/local/phantomjs/bin/phantomjs
Username for 'https://github.com': 
> contextify@0.1.15 install /home/travis/build/pcottle/learnGitBranching/node_modules/jquery/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild
make: Entering directory `/home/travis/build/pcottle/learnGitBranching/node_modules/jquery/node_modules/jsdom/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
  SOLINK_MODULE(target) Release/obj.target/contextify.node
  SOLINK_MODULE(target) Release/obj.target/contextify.node: Finished
  COPY Release/contextify.node
make: Leaving directory `/home/travis/build/pcottle/learnGitBranching/node_modules/jquery/node_modules/jsdom/node_modules/contextify/build'
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

```

its weird. maybe something is wrong with the travis setup or i have an outdated dependency? i dont think your PR necessarily kicked off this problem, it was just sent after something happened. weird.

im on a work trip all week but ill try to look at this on the weekend and see what the problem is.

**Comment by pcottle** [comment]
Alright I fixed the build in #357 and since this should merge cleanly (which means build shouldnt break) lets do it! thanks again @JuhoKang

**Pull request merged**
