### PR TITLE
add git gc command

### LINKED ISSUE #957: `git gc` implementation
It would be cool if LGB had a little tiny garbage-collector. Nothing fancy with packs, just to remove all of the commits not pointed to by a branch. I could *probably* implement this.

### PR DESCRIPTION
**Pull request by thetayloredman**
Little attempt at doing #957.

Closes #957.

This probably needs an animation as if it was traversing from HEAD down.

### CODE REVIEW

**Review by ilikestohack — APPROVED** [review]

**Comment by pcottle** [comment]
I forgot I had the prune tree command, so convenient!

**Comment by pcottle** [comment]
checked this out locally, will push the site now :)

**Comment by thetayloredman** [comment]
How would we manage to do an animation or is it too obscure to need one?

**Comment by pcottle** [comment]
The removed commits don't do any kind of animation but the tree does gracefully animate to its new layout, so it looks pretty decent.

heres a demo:
https://learngitbranching.js.org/?NODEMO&command=git%20commit;%20git%20branch%20-f%20main%20C1;%20gc;%20git%20gc

**Comment by thetayloredman** [comment]
Yeah. Would it be better to somehow animate the traversal from every ref in the repository (marking every commit as needed)? Also, please make sure you test it with tags

**Comment by pcottle** [comment]
uh oh you're right, tags break it:
https://learngitbranching.js.org/?NODEMO&command=git%20commit;git%20tag%20foo;%20git%20branch%20-f%20main%20C1;%20gc;%20git%20gc

I think animating each commit is unnecessary, we already visually show which ones are eligible for pruning by modifying the transparency

**Comment by pcottle** [comment]
tags fixed in that commit ^^

**Comment by thetayloredman** [comment]
@pcottle Isn't the prune tree thing used for converting from Git to Hg, and if so, will that break the Hg switch?

**Comment by pcottle** [comment]
It's a little undefined for what to do with tags in mercurial mode. But before the fix above, there was a floating tag that had the underlying commit deleted so that's probably more broken than after this fix.

**Pull request merged**
